# This workflow runs for every pull request to lint and test the proposed changes.

name: Check

on:
    pull_request:

jobs:
    build_and_test:
        name: Build & Test
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                node-version: [ 18, 20, 22, 24 ]

        steps:
            -   uses: actions/checkout@v5
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v6
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Install pnpm and dependencies
                uses: apify/workflows/pnpm-install@main
            -   name: Run Tests
                run: pnpm test

    lint:
        name: Lint
        needs: [ build_and_test ]
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v5
            -   name: Use Node.js 24
                uses: actions/setup-node@v6
                with:
                    node-version: 24
            -   name: Install pnpm and dependencies
                uses: apify/workflows/pnpm-install@main
            -   run: pnpm lint
